#use-database set to true if you want to use database, defaults to local storage
use-database: false

#database settings
host: "my_host.com"
port: 3306
database: "database"
username: "username"
password: "password"

#debug mode, set TRUE if you want debug messages
debugmode: false
