#update_alive rate (in seconds) (increases accuracy on server crashes and sum table's data for currently online players)
update_delay: 30

#database settings
host: "my_host.com"
port: 3306
database: "database"
username: "username"
password: "password"

#debug mode, set TRUE if you want debug messages
debugmode: false
