name: TimeSheet
main: TimeSheet.Main.TimeSheet
version: 1.0
api-version: 1.13
depend: []
commands:
  totaltime:
    description: total time played on server
    permission:
    permissions: []
    permission-message: Error permissions
    usage: "Usage: /totaltime"